name: Deploy to EC2 via Docker Compose

on:
  workflow_run:
    workflows: ["Docker Compose Test"]  # ← 이 이름이 중요
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Clean remote directory
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@13.124.106.139 "
            find /home/bitnami/node_app_docker -mindepth 1 -delete
          "

      - name: Upload project to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . bitnami@13.124.106.139:/home/bitnami/node_app_docker/

      - name: Deploy with Docker Compose on EC2
        run: |
          ssh -tt -o StrictHostKeyChecking=no bitnami@13.124.106.139 << 'EOF'
            cd /home/bitnami/node_app_docker
            docker compose down || true
            docker compose up -d --build
            docker compose ps
            echo "✅ EC2 배포 완료"
            exit 0
          EOF
